
import asyncio
import logging
import sys
import os

# Add parent dir to path to find 'database' module
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from sqlalchemy import select, text
from database.db_connect import engine, AsyncSessionLocal, Base
from database.models import User, Student, Staff

# Setup Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def migrate_users():
    logger.info("Starting Users Table Migration...")

    async with engine.begin() as conn:
        # Create table if not exists (using SQLAlchemy metadata)
        # Note: In a real alembic setup, this would be an autogenerated migration.
        # Here we force create just the new table if missing.
        await conn.run_sync(Base.metadata.create_all)
        logger.info("Ensured 'users' table exists.")

    async with AsyncSessionLocal() as session:
        # 1. Migrate Students
        logger.info("Migrating Students...")
        result = await session.execute(select(Student))
        students = result.scalars().all()
        
        migrated_count = 0
        for s in students:
            # Check if user already exists
            existing = await session.scalar(select(User).where(User.hemis_login == s.hemis_login))
            if existing: 
                logger.info(f"User {s.hemis_login} already exists. Skipping or Updating.")
                # Optional update logic here if needed
                continue

            new_user = User(
                hemis_login=s.hemis_login,
                username=s.username, # Migrating username
                role="student",
                full_name=s.full_name,
                short_name=s.short_name,
                image_url=s.image_url,
                phone=s.phone,
                hemis_id=s.hemis_id,
                hemis_token=s.hemis_token,
                hemis_password=s.hemis_password,
                
                university_name=s.university_name,
                faculty_name=s.faculty_name,
                specialty_name=s.specialty_name,
                group_number=s.group_number,
                level_name=s.level_name,
                semester_name=s.semester_name,
                education_form=s.education_form,
                education_type=s.education_type,
                payment_form=s.payment_form,
                student_status=s.student_status,
                
                province_name=s.province_name,
                district_name=s.district_name,
                accommodation_name=s.accommodation_name,
            )
            session.add(new_user)
            migrated_count += 1
        
        await session.commit()
        logger.info(f"Migrated {migrated_count} students.")

        # 2. Migrate Staff
        logger.info("Migrating Staff...")
        result = await session.execute(select(Staff))
        staff_list = result.scalars().all()
        
        migrated_staff_count = 0
        for st in staff_list:
            # Staff might not have 'hemis_login' in the same reliable way as Student
            # Currently Staff model has 'hemis_login' (from my analysis of previous files). 
            # If not, we might need to fallback to jshshir or some identifier.
            # Assuming hemis_login exists and is populated based on login.
            
            # Note: Staff model uses 'jshshir' as unique ID.
            
            login_key = st.jshshir
            if not login_key:
                logger.warning(f"Staff {st.id} ({st.full_name}) has no JSHSHIR. Skipping.")
                continue

            existing = await session.scalar(select(User).where(User.hemis_login == login_key))
            if existing:
                continue

            # Need to fetch university/faculty names if they are relations
            # For migration simplicity, if they are relations ID, we might need JOINs or lazy load.
            # Assuming basic data for now.
            
            new_user = User(
                hemis_login=login_key,
                role="staff", # Or st.role.value
                full_name=st.full_name,
                phone=st.phone,
                # Staff might not have all student fields, leave them null
                # We can store 'position' in 'specialty_name' or add a new field later?
                # For now map essential identity.
                specialty_name=st.position, # Example mapping 
            )
            session.add(new_user)
            migrated_staff_count += 1
            
        await session.commit()
        logger.info(f"Migrated {migrated_staff_count} staff members.")

    logger.info("Migration Completed Successfully.")

if __name__ == "__main__":
    asyncio.run(migrate_users())
