# Generated by Django 5.2.3 on 2025-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='social_score',
            field=models.FloatField(default=0.0),
        ),
    ]
