# Generated by Django 5.2.3 on 2025-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_student_education_score_student_social_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
