# Generated by Django 5.2.3 on 2025-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
