# Generated by Django 5.2.3 on 2025-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tutor_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
