# Generated by Django 5.2.3 on 2025-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_student_education_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='type',
            field=models.CharField(choices=[('education', 'Education'), ('social', 'Social'), ('special', 'Special')], default='special', max_length=10),
        ),
    ]
