# Generated by Django 5.2.3 on 2025-07-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_inspector_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='faculty',
            new_name='group',
        ),
    ]
