# Generated by Django 5.2.3 on 2025-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_faculty_tutor_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='group',
        ),
        migrations.AddField(
            model_name='tutor',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='user.group'),
        ),
    ]
