# Generated by Django 5.2.3 on 2025-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_group_remove_tutor_group_tutor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
