# Generated by Django 5.2.3 on 2025-06-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_student_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Criterion',
                'verbose_name_plural': 'Criteria',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='user.student')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('preferred', 'Preferred')], max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.student')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.attempt')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='attempt_items', to='application.answer')),
            ],
            options={
                'verbose_name': 'Attempt Item',
                'verbose_name_plural': 'Attempt Items',
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='answers',
            field=models.ManyToManyField(related_name='attempts', to='application.attemptitem'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='applications/files/')),
                ('score', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.student')),
            ],
            options={
                'verbose_name': 'Application Item',
                'verbose_name_plural': 'Application Items',
                'ordering': ['score', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_throughs', to='application.application')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_through', to='application.criterion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_through', to='application.item')),
            ],
            options={
                'verbose_name': 'Criterion Through',
                'verbose_name_plural': 'Criterion Throughs',
                'unique_together': {('application', 'item')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='applications', through='application.CriterionThrough', to='application.item'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=30)),
                ('text', models.TextField()),
                ('answers', models.ManyToManyField(blank=True, related_name='questions', to='application.answer')),
                ('variants', models.ManyToManyField(blank=True, related_name='variant_questions', to='application.answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_items', to='application.question'),
        ),
    ]
