# Generated by Django 5.2.3 on 2025-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_attempt_difficulty_question_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
    ]
