# Generated by Django 5.2.3 on 2025-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
