# Generated by Django 5.2.3 on 2025-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_attempt_is_completed_attemptitem_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
