# Generated by Django 5.2.3 on 2025-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_attempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptitem',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
