# Generated by Django 5.2.3 on 2025-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_attemptitem_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
