# Generated by Django 5.2.3 on 2025-07-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_criterion_preferred'),
        ('user', '0004_student_education_score_student_social_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.student'),
        ),
    ]
