# Generated by Django 5.2.3 on 2025-07-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_application_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
