# Generated by Django 5.2.3 on 2025-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_attempt_difficulty_remove_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_education_score_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_social_score_approved',
            field=models.BooleanField(default=False),
        ),
    ]
