# Generated by Django 5.2.3 on 2025-07-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
