# Generated by Django 5.2.3 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_item_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('education_type', models.CharField(max_length=100)),
                ('education_language', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('complete_quota', models.IntegerField()),
                ('incomplete_quota', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotas',
                'unique_together': {('speciality', 'education_type', 'education_language', 'level')},
            },
        ),
    ]
