# Generated by Django 5.2.3 on 2025-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='quota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
