# Generated by Django 5.2.3 on 2025-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_quota_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='student_uploadable',
            field=models.BooleanField(default=True),
        ),
    ]
