# Generated by Django 5.2.3 on 2025-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_criterion_student_uploadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
