# Generated by Django 5.2.3 on 2025-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
