# Generated by Django 5.2.3 on 2025-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_rename_result_appeal_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='appeals/responses/'),
        ),
    ]
